service: serverless-github-action
frameworkVersion: '3'

provider:
    name: aws
    runtime: python3.10
    stage: dev
    region: eu-west-1

functions:
    hello:
        handler: src/handler.hello
